#!/usr/bin/env bash
# Generate config.mk: header probes only (HAVE_*). See Makefile for CFLAGS rationale.
set -euo pipefail

# macOS: `xcrun clang` (same as Makefile DEFAULT_CC). Bare clang from `xcrun -f clang`
# omits -isysroot and does not resolve <stdio.h> against the SDK.
if [[ "$(uname -s)" == "Darwin" ]]; then
  if [[ -z "${CC:-}" ]]; then
    if command -v xcrun >/dev/null 2>&1; then
      CC="xcrun clang"
    else
      CC=clang
    fi
  fi
else
  : "${CC:=clang}"
fi
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_MK="${REPO_ROOT}/config.mk"
TMPDIR="${TMPDIR:-/tmp}"
WORK="$TMPDIR/cmatrix-configure-$$"

cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT
mkdir -p "$WORK"

append_probe() {
  local h="$1" d="$2"
  printf '#include <%s>\nint main(void){return 0;}\n' "$h" >"$WORK/probe.c"
  # shellcheck disable=SC2086
  if $CC -std=c17 -fsyntax-only "$WORK/probe.c" >/dev/null 2>&1; then
    defs+=("$d")
  fi
}

defs=()

append_probe sys/ioctl.h -DHAVE_SYS_IOCTL_H
append_probe unistd.h -DHAVE_UNISTD_H
append_probe termios.h -DHAVE_TERMIOS_H
append_probe termio.h -DHAVE_TERMIO_H
append_probe getopt.h -DHAVE_GETOPT_H

{
  echo "# Generated by configure.sh — do not edit. Regenerate: ./configure.sh"
  if ((${#defs[@]} > 0)); then
    printf 'CMATRIX_CPPFLAGS := %s\n' "${defs[*]}"
  else
    printf 'CMATRIX_CPPFLAGS :=\n'
  fi
} >"$CONFIG_MK"

echo "Wrote ${CONFIG_MK}"
